# Web Server nginx

services:
  web:
    image: nginx:1.29
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/fed_conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - fed-network

  # DB custom image
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_HOST=${MARIADB_ROOT_HOST}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - fed-network

  # App custom image
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    container_name: fed.fr
    depends_on:
      - db
    networks:
      - fed-network

volumes:
  db_data:


networks:
  fed-network:
    driver: bridge
